[package]
name = "gaming_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
beryllium = "0.13.3-alpha.2"
imagine = "0.0.5"
[dev-dependencies]
